### PR TITLE
fix(core): Add volume to RabbitMQ service

### PR DESCRIPTION
**Pull request by netoax**
What does this implement/fix? Explain your changes.
---------------------------------------------------
In order to enable RabbitMQ persistence, this patch adds a Docker volume
to it and updates the RabbitMQ hostname to avoid searching for data in a
different directory every time the service is deployed.

Where has this been tested?
---------------------------

**Operating System/Platform:** macOS Darwin - 18.0.0

**NPM Version:** 6.14.4

**NodeJS Version:** v12.16.2

### CODE REVIEW

**Review by lcbm — APPROVED** [review]
LGTM :smile:

**Comment by luigiluz** [comment]
I've tested it and it's happening something weird with connector after removing and redeploying rabbitmq service. Still don't know what is causing this, just commenting it here to keep this issue tracked.

**Comment by netoax** [comment]
> I've tested it and it's happening something weird with connector after removing and redeploying rabbitmq service. Still don't know what is causing this, just commenting it here to keep this issue tracked.

Nice, @luigiluz. I will repeat my tests to guarantee weird bugs aren't appearing. I guess it could be something related to the client itself.

**Comment by netoax** [comment]
Update: Despite the bug we found in the connector (corner case - BLI-294), the persistence is working fine and this patch must advance to approval and merging.

**Review by esdrasjnr — APPROVED** [review]
LGTM!

**Pull request merged**
